### ISSUE TITLE
Does it work with commodities and stocks?

### ISSUE THREAD

**Issue by kenorb** [giuse88/duka#12]
As in title, e.g. E_YHOO, E_BAY, E_AAPL, E_AMZN, etc?

**Comment by giuse88** [comment]
I don't think so. The dukacopy downloader supports only FX and CDF and some commodities.

**Comment by kenorb** [comment]
I've got this php script ([`dl_bt_dukascopy.php`](https://github.com/FX31337/FX-BT-Scripts/blob/master/dl_bt_dukascopy.php)) which may support it, but I'm looking for Python implementation as well.

**Comment by giuse88** [comment]
I am using the same feed, so if it works for the php script it should also work for `duka`. Give it a try:
`duka E_YHOO E_BAY  E_AAPL E_AMZN`
It should download all yesterday ticks for those instruments.

**Comment by giuse88** [comment]
@kenorb Hi, 
I tried to query dukascopy feed with the symbols in your script. Are you sure that the script is working right now? When I query for a stock, the server returns 404.

For example:
```
wget http://www.dukascopy.com/datafeed/E_T/05/2/15h_ticks.bi5
```
Returns an error.

**Comment by kenorb** [comment]
I think I had the same issue, so that's why I was wondering if that works for you. The data is there, but probably the URLs changed or the names, or they removed some of them.

E.g. this URL works:

> https://www.dukascopy.com/datafeed/LIGHTCMDUSD/2016/04/23/03h_ticks.bi5

And other found at [dukascopy historical page](https://www.dukascopy.com/swiss/english/marketwatch/historical/).

**Comment by giuse88** [comment]
The link you posted works because it is one of the instrument in the historical data downloader. duka is able to download all instruments allowed in the historical downloader. Unfortunately only German stocks are there. 

For instance, SAP stock works
```
duka SAPDEEUR
```

**Comment by giuse88** [comment]
Closing as it is not an issue.
