### ISSUE TITLE
please tell me which python should i select for duka?

### ISSUE THREAD

**Issue by nervending** [giuse88/duka#15]
use 3.4.2 error log:
File "/root/.pyenv/versions/3.4.2/lib/python3.4/site-packages/duka/core/fetch.py", line 16
    async def get(url):
            ^
SyntaxError: invalid syntax

use 3.5.2 error log:
File "/root/.pyenv/versions/3.5.2/lib/python3.5/lzma.py", line 26, in <module>
from _lzma import *
ImportError: No module named '_lzma'

**Comment by nervending** [comment]
i got it, should use 3.5
maybe some system config error
i use pyenv install python, and switch to 3.5.0 
report same error :
ImportError: No module named '_lzma'

**Comment by nervending** [comment]
i need install liblzma-dev, but after install, it's not ok.

**Comment by nervending** [comment]
and reinstall python 3.5.x, that all ok.

**Comment by giuse88** [comment]
Sorry for the delay in answering, I was travelling yesterday.  Duka uses the `ansync` syntax and requires a python 3.5 interpreter. Glad you sorted out.
