### ISSUE TITLE
Candle in the usage are incorrect

### ISSUE THREAD

**Issue by uraxy** [giuse88/duka#16]
> ```
> -c CANDLE    use candles instead of ticks. Accepted values 1M 5M 10M 15M 30M 1H 4H 1D
> ```

Values should be M1 M5 M10 ...

duka is very useful!

**Comment by giuse88** [comment]
Thanks 😀😀. i ll fix as soon as I have a moment!

**Comment by giuse88** [comment]
Duplicated of #17
