### ISSUE TITLE
Add candle output

### ISSUE THREAD

**Issue by giuse88** [giuse88/duka#2]
It would be nice to have the option to aggregate ticks with different timeframe. For example, I could add a command line option like : 
```bash
--timeframe=M1 // for 1M
--timeframe=M2 // for 2M
--timeframe=H1 // 1 hour
--timeframe=T30 // 30 ticks
```

**Comment by javagg** [comment]
1. --timeframe or (--candle) should allow multiple values, this way we can generate bardata with different frequency in one downloading request.
2. ask_volume and bid_volume should be handled in generated files.

btw, you did a wonderful job! thanks!

**Comment by giuse88** [comment]
> --timeframe or (--candle) should allow multiple values, this way we can generate bardata with different frequency in one downloading request.

You can always build candles with larger period from candles with shorter period. If I an additional time frame is added to the downloaded file, it will increase its size without actually adding any new information. I'll think about it though. 

>  ask_volume and bid_volume should be handled in generated files.

Very true. I'm not 100% sure how to aggregate volume data. I need to understand how trading charting software does it and then I will implement it in Duka.  

In addition I would be nice to have an option which allows how to specify which *ask*,*bid* or *mid* price should be used to build the candles. 

> btw, you did a wonderful job! thanks!

Thank you. :)
