### ISSUE TITLE
How to find a list of all the symbols?

### ISSUE THREAD

**Issue by wardnath** [giuse88/duka#22]
Is there a list somewhere of all the symbols that can be downloaded?

**Comment by wardnath** [comment]
For example what would be the symbol for us brent crude oil, if any?

**Comment by giuse88** [comment]
Hi @wardnath, 

Yes, there is. You can find the full list of downloadable products [here](https://www.dukascopy.com/swiss/english/marketwatch/historical/). 

For instance, oil prices can be dowloaded using these two identifiers:
- **BRENT.CMD**  US brent crude oil
- **LIGHT.CMD**   US light crude oil

**Comment by wardnath** [comment]
Thank you @giuse88. To add on to your comment, I've found the symbol name needs to match the naming scheme for the intstrument constants shown here:

https://www.dukascopy.com/client/javadoc/com/dukascopy/api/Instrument.html

for example BRENT.CMD would be `BRENTCMDUSD`. Not all instruments listed on my link can be downloaded, for example:

 ```$ duka AAPLUSUSD -s 2016-12-01``` 

doesn't work - the symbol needs to be on the link you posted.
