### ISSUE TITLE
XAUUSD and XAGUSD history data error

### ISSUE THREAD

**Issue by wbdu** [giuse88/duka#28]
i download XAUUSD and XAGUSD history data using:
#duka EURUSD -s 2016-04-12 -e 2016-04-12
#duka XAGUSD -s 2016-04-12 -e 2016-04-12

i found last row of file start with "2016-04-12 22:59:57.731000,0.16153,0.16118,200000,10000" and "2017-01-10 22:59:52.340000,11.86402,11.86099,370,370".
time is error, but rows count is right, why?

and i found the digits of XAUUSD and XAGUSD is error too.

how i can do?

**Comment by EvianZhow** [comment]
@wbdu duplicated with https://github.com/giuse88/duka/issues/23 , and a fix is here: https://github.com/giuse88/duka/pull/24

**Comment by devbar** [comment]
Ether duplication of #23 nor fixed in #24. I have the same issue in latest build of branch. **The issue is: The last row of a file is 22:59:... but expected is 23:59.**

Please re-open
