### ISSUE TITLE
No module named 'setuptools.wheel' when installing duka

### ISSUE THREAD

**Issue by yomoko** [giuse88/duka#30]
I got this error when trying to install duka. 
> Failed building wheel for duka

What's wrong with it? Please help. Thanks.

![image](https://user-images.githubusercontent.com/33768560/33732310-1b699694-db54-11e7-9626-dd9fade9a505.png)

**Comment by evianzhow** [comment]
Are `setuptools` correctly installed on your system? From the traceback above, I can't get enough information. Please tell us more.

**Comment by yomoko** [comment]
@EvianZhow  Yes. I am using Anaconda. Setuptools is installed by default.(setuptools (36.5.0.post20170921)). I tried to reinstall duka again. The error is gone(I don't know why). But I still can't use it somehow. As you see from the screenshot, after I import duka and entered duka -h, it says module not defined. So what went wrong? I am using 64 bit python. What other information to do you need?
![image](https://user-images.githubusercontent.com/33768560/33806521-70160a84-dd97-11e7-8206-23fb56cfef58.png)

**Comment by evianzhow** [comment]
duka is a command-line tools. So I think import it as a library will not work.

**Comment by yomoko** [comment]
@EvianZhow  What do you mean? Even if I don't import it, it's not usable, when I followed the instruction by entering duka -h OR duka EURUSD, for example, it didn't work. So what went wrong?

**Comment by evianzhow** [comment]
@yomoko What's your mean about 'didn't work'? Do you have a detailed traceback?

**Comment by yomoko** [comment]
@EvianZhow  As you see from my screenshot, both duka and -h are not defined. So what's the correct way of using it or anything went wrong?

**Comment by evianzhow** [comment]
You are not typing under command line, from your screenshot, you are typing under Python REPL. Type duka related command into cmd or powershell if you are using Windows.

**Comment by yomoko** [comment]
@EvianZhow  No wonder. Thanks. By the way, is it possible to change the candle time interval to New York time EST instead of default GMT?

**Comment by evianzhow** [comment]
That feature should be in the 2.1 release, but we encounter some issues, see #29 for more information.

**Comment by yomoko** [comment]
@EvianZhow I read the #29 you mentioned. But is it possible to:
1. Make the day interval begin at 17:00 EST(which is the official start time of forex) instead of 00:00 local time? 
2. D/L other time frequency such as 2H, 8H, weekly, daily, other than those available
3. D/L ask price also
Thanks.
