### ISSUE TITLE
what does default data columns mean ?

### ISSUE THREAD

**Issue by henryatman** [giuse88/duka#35]
hi, dude,

very thanks your wonderful tool, but i have some confusion about download data.
like this 

2018-07-27 00:00:00.254000,1.16438,1.16436,1500000,2620000
2018-07-27 00:00:00.548000,1.16438,1.16434,7610000,1500000
2018-07-27 00:00:00.914000,1.16435,1.16432,1250000,3070000

what does each columns mean? is there no any document to describe this.

can you describe more information? columns mean and units mean

thanks

**Comment by henryatman** [comment]
i found out very strange thing 

url_info = {
        'currency': symbol,
        'year': day.year,
        'month': day.month - 1,
        'day': day.day
    }

why real download file need minus -1 ,?

**Comment by cjlv91** [comment]
It means Open, Close, High, Low

**Comment by kemalure** [comment]
I know this is closed but the answer in incorrect. Correct labels for the data frame are Ask_Price, Bid_Price, Ask_Volume, Bid_Volume
