### ISSUE TITLE
CSV format

### ISSUE THREAD

**Issue by holographix** [giuse88/duka#44]
Hi y'all,
I was downloading a few dataset to test out a strategy, but I cannot find anywhere an explanation on how the data are constructed.
I got a CSV with no headers, so I can't tell if the candles are OHLC or OLHC or HLOC or whatever other permutation of those. 
Maybe somebody can shed some light on this?
Thanks in advance.

Ah, FWIW this is the command I used to get the dataset I was about to backtest my strat onto:

`duka GBPJPY -s 2018-01-01 -e 2022-12-01 -t 2 -c D1`

**Comment by ghost** [comment]
I haven't used this in years, but if you want to figure it out simply use another source and then you'll know. i.e. check the OHLC values on tradingview.com for a particular currency then you'll know the mapping.

**Comment by holographix** [comment]
Nevermid, I figured out that if you download a dataset using their web tool you can have the headers.
and just for the sake of it the order is 
`Local time,Open,High,Low,Close,Volume`
